# main.<EC2_IP>.nip.io  ->  web-main:80
# dev.<EC2_IP>.nip.io   ->  web-dev:80

server {
    listen 80;
    server_name main.18.215.251.196.nip.io;

    location / {
        proxy_pass http://web-main:80;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80;
    server_name dev.18.215.251.196.nip.io;

    location / {
        proxy_pass http://web-dev:80;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80 default_server;
    return 444;
}